apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "istio-lib-helm.fullname" . }}
  labels:
    {{- include "istio-lib-helm.labels" . | nindent 4 }}
spec:
  host: {{ include "istio-lib-helm.fullname" . }}
  subsets:
  {{- range $tags := .Values.image.tags }}
    #reemplace el punto por guion bajo
    - name: "v{{ $tags.version | replace "." "" }}"
      labels:
        app: {{ include "istio-lib-helm.fullname" $ }}
        version: {{ $tags.version }}
  {{- end }}
