apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "istio-lib-helm.fullname" . }}
  labels:
    {{- include "istio-lib-helm.labels" . | nindent 4 }}
spec:
  host: {{ include "istio-lib-helm.fullname" . }}
  # trafficPolicy:
  #   connectionPool:
  #     http:
  #       http1MaxPendingRequests: 1
  #       maxRequestsPerConnection: 1
  #   outlierDetection:
  #     consecutiveErrors: 1
  #     interval: 1s
  #     baseEjectionTime: 3m
  #     maxEjectionPercent: 100
  {{- if .Values.destinationRule.trafficPolicyEnabled  }}
  trafficPolicy: {{ toYaml .Values.destinationRule.trafficPolicy | nindent 4 }}
  {{- end }}
  subsets:
  {{- range $tags := .Values.image.tags }}
    #reemplace el punto por guion bajo
    - name: "v{{ $tags.version | replace "." "" }}"
      labels:
        app: {{ include "istio-lib-helm.fullname" $ }}
        version: "v{{ $tags.version | replace "." "" }}"
  {{- end }}
